version: "3"

services:
  web:
    build: .
    container_name: app
    image: alotropo/tools
    command: uvicorn main:app --host 0.0.0.0
    networks:
      - node-network
    volumes:
      - .:/code
      # - ./tools/src/problems/domain/value_object/.:/code/src/problems/domain/value_object
      # - ./static:/code/static/

    environment:
      - PYTHONPATH=/code/
    tty: true
    # env_file:
    #   - ./.env
    ports:
      - 8000

  nginx:
    image: alotropo/nginx
    container_name: nginx_app
    networks:
      - node-network
    volumes:
      # #   - staticfiles:/app/static/
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/build:/var/www/html
      # - ./nginx/certs:/etc/nginx/certs

    ports:
      - 80:80
    depends_on:
      - web

networks:
  node-network:
    driver: bridge
